version: '3.8'

services:
  app:
    image: 'ticket-service:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Ticket-service
      - SPRING_DATASOURCE_USERNAME=compose-admin
      - SPRING_DATASOURCE_PASSWORD=compose-Zxcdsaqwe

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-admin
      - POSTGRES_PASSWORD=compose-Zxcdsaqwe